### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#12]
Opening issue to create a navigation component for the site.

**Comment by rwx-yxu** [comment]
Reassigning to myself.

**Comment by rwx-yxu** [comment]
Pushing back to dev.

**Comment by rwx-yxu** [comment]
Need to raise a new pull request to add unit test for nav bar component.

**Comment by advweb-grp1** [comment]
Done
