### ISSUE TITLE
core: Fire store setup

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#17]
Get the initial config to make firestore accessible.

Main objectives are to make main compatible with .env files for the fire store config.

I need to make the documents and collections manually in the firebase console as well.

**Comment by rwx-yxu** [comment]
The CSV file provided to us for hcm is left to the developers to decide on how we want to process the data.

**Comment by rwx-yxu** [comment]
Will work on the happy path first with the firestore configs before parsing or checking on start up.

**Comment by rwx-yxu** [comment]
TODO:
- [ ] create directory called 'firebase' with the file 'database.js'
- [ ] database.js should store get the firebase config details from a .env file
- [ ] Create the initial db documents and collections on firebase site as according to the ERD defined from https://github.com/advweb-grp1/advanced-web-final-year-project/issues/2#issuecomment-1469941542
- [ ] Create a test document that has the key value {"Status": "Active"}
- [ ] Create a test end point that displays the test document to verify that the db app can contact the db

**Comment by rwx-yxu** [comment]
There are larger implications how that I think about the .env file because I think that for this assignment, we need to make that available on the repo but I do not feel comfortable with putting API keys on a public GitHub repo.

Need to think of a way to have something like a .env.local file for dev and allow for .env to be pushed to the repo once the project is done.

**Comment by rwx-yxu** [comment]
Instead of a test document, would it be more sensible to have a "Setup" document that has values that tracks if the app has been setup?
I could still have the test key value but, I could also have a key value for "{hcm_data_uploaded:false}"? So, in the app, I check for that and if it is false, I find the csv and parse it to post onto the db. This would be better than a standalone script that is a throw away and it wouldn't be a throwaway end point that we would have open.

**Comment by LiamSingh64** [comment]
> Need to think of a way to have something like a .env.local file for dev and allow for .env to be pushed to the repo once the project is done.

So the pushed .env file with just access variables from the .env.local file?

**Comment by rwx-yxu** [comment]
No. The .env file is one that is available publicly. .env.local file will just be for local development that is not pushed to GitHub. Reason for making the .env file public is because I think that Ismail wants the config files for firebase visible along with the account passwords ect for the adv-grp1 accounts so we need to make a .env file publicly visible.

**Comment by rwx-yxu** [comment]
We will use .env.local for now and make push .env file public at the end of the project.

> .env to be pushed to the repo once the project is done.

Wouldn't want the firebase config settings to be pushed right now during development. Saves time with putting .env in .gitignore now and then taking it off at the end to push .env. Whereas I can put .env.local in .gitignore and not bother with messing with that file at all.

**Comment by rwx-yxu** [comment]
Noticed that there is already a branch for core/fire-base-setup. Need to check with @LiamSingh64 on if he wants to dev it since he already has two commits in there.

**Comment by rwx-yxu** [comment]
Taking back ownership of dev after clarifying Liams stance.

**Comment by rwx-yxu** [comment]
Vite has a way to manage env files https://vitejs.dev/guide/env-and-mode.html

**Comment by rwx-yxu** [comment]
Going to use csv-parser to parse the csv and fs to find the csv in the current directory.

**Comment by rwx-yxu** [comment]
Trying to do the parsing right now and I am getting this error when trying to use fs to read the file Cannot access "fs.existsSync" in client code.

**Comment by rwx-yxu** [comment]
Starting to learn that there is a difference between vite and nodejs. vite is the frontend development server which runs in the browser means that it is separate from the server side nodejs. This means that vite cannot have direct access to server files and cannot exit using process.exit(1).

**Comment by rwx-yxu** [comment]
Not sure if it is worthwhile to upload the hcm csv file
