### ISSUE TITLE
Core/Layout

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#18]
Raising issue to define a general layout for the project. This should mostly involve removing all of the default css settings created by vueJS and create the divs using bootstrap to define the grid layout we want. Only requirement from my POV is that we have a nav, main and footer section really. The nav and footer should be static and main should display the views that will contain components.

**Comment by D4ni3l8** [comment]
I was thinking of making the layout of the page with a cardiomyopathy description, possible symptoms and causes, different types of cardiomyopathy and who it affects. 
I looked at different sites to get ideas such as NHS and BHF.

**Comment by rwx-yxu** [comment]
Changing dev to me and switching back to development.
Fix:
- Failing github action
- Resolve issue with nav bar buttons not routing to the selected view components.
