### ISSUE TITLE
feature/data-grid

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#39]
A data grid which displays all of the high priority fields in one table. Should have actions column for view, update and delete. Delete will be implemented via #9 .
Requirements:
- data page
- update page
- view page: The page should display the entire record of the participant (includes non high priority fields)
- need high priority filter when getting fields back from firestore.

**Comment by advweb-grp1** [comment]
Can only be started when #10 has been merged in.

**Comment by rwx-yxu** [comment]
Yongle will be dev along with the #9

**Comment by rwx-yxu** [comment]
Data grid component is already up so it is just a matter of switching the actions toggle to true and pass through the delete action for the button. New nav bar item will be introduced called "data"
