### ISSUE TITLE
Use Case: Login User

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#4]
A user must login to the system to access data, add or delete data.

## Basic path
1. The use case starts when a user indicates that he/she wants to login.
2. The system requests the username and password.
3. The user enters his/her username and password.
4. The system verifies the username and password against all registered users.
5. The system starts a login session and displays a welcome message.

## Alternative Paths
Step 4:
If username is invalid, the use case goes back to step 2.

Step 4:
If the password is invalid, the system requests that the user re-enter the password. When the user enters another password, the use case continues with step 4 using the original username and new password.

## Exception Paths
The system may abandon login after 5 unsuccessful attempts.

## Preconditions
The user is registered.
The username is the user’s email address.

## Postconditions
The user can now add data, delete data, query data and visualise data.

**Comment by advweb-grp1** [comment]
Reference the page design in #3 for the login page.

**Comment by advweb-grp1** [comment]
Login will be authenticated via Firebase.

**Comment by rwx-yxu** [comment]
Will need a Login form component - to capture the user's username and password

**Comment by rwx-yxu** [comment]
## User Authentication
* Implement Firebase Authentication with email and password
* Set up login form with input validation (e.g., email format and required fields)
* Connect login form with Firebase Auth sign-in method
* Handle login errors and display appropriate messages (e.g., wrong password, unregistered user)
* Implement a mechanism to track unsuccessful login attempts and lockout after 5 attempts

## Route Guards and User Sessions
* Implement route guards to protect authenticated routes (e.g., dashboard, query, data manipulation)
* Check user's authentication state using Firebase Auth on app initialization and apply route guards accordingly
* End user session on logout and redirect to the login page

**Comment by rwx-yxu** [comment]
"The system may abandon login after 5 unsuccessful attempts." line doesn't specify what is the mechanism to get the user back to being able to log back in? 
May just be a time out of 30 mins then allow them to log back in?

**Comment by rwx-yxu** [comment]
For route guards, I should hide the nav items so that only logged in users can see the query button for example. This will require a change to the nav bar component

**Comment by rwx-yxu** [comment]
Need to also implement log out button as well once logged in.
