### ISSUE TITLE
core/hcm_data

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#40]
# Problem
During dev of the dashboard, page exceeded the read limits for firestore at 52k reads!
![image](https://user-images.githubusercontent.com/126356360/232471170-2d7e3c4b-d974-4f7f-bdd6-777e7c1415f3.png)
Firestore only allows for 50k reads per day.
![image](https://user-images.githubusercontent.com/126356360/232471241-47104686-1fb5-44a5-b50e-31fbb62aef9a.png)
## Hotfix
Upload a cut down version of the hcm csv data called hcm_dev.csv. Cut down to like 10 records or so.

## Fix
Create a pinia store that loads the hcm data when the application is loaded to reduce reads when going to the dashboard view.

**Comment by advweb-grp1** [comment]
Hot fix will be dev by liam.

**Comment by rwx-yxu** [comment]
Keeping issue open to implement the pinia store.
