### ISSUE TITLE
feature/user-profile

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#44]
Create user profile page that will display their user data that they used when registering.

Allow user to update info.

**Comment by AymanReh** [comment]
For the update user page I think allowing users to edit everything execpt for the password, since the password can already be edited using #6. Was thinking of using the same layout of register user since I think that's the best layout for this type of page.

**Comment by AymanReh** [comment]
Navbar must also be edited to add the edit user profile page

**Comment by AymanReh** [comment]
Need to update nav bar to add edit profile for users who are logged in. Currently im going to the edit page using the url which logs me out when i go to the url page, so an update to the nav bar or route guard will stop this from happening.

**Comment by advweb-grp1** [comment]
Only new item for the nav bar should be "Profile" button. The update user page should be a button on the profile page that takes them to that. There should also be another button to take the user to the reset password page.
