### ISSUE TITLE
Core/scaffold

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#5]
This issue is raised to track the basic vue project init. 
The requirements should be:
- [x]  VueJS app init
- [x] Router with empty views for each page. Need site map first.
- [x] Add bootstrap

* Database config? This will require a separate issue for db set up with firestore.
* Add .gitignore for the env file. Part of the DB setup.

**Comment by rwx-yxu** [comment]
Testing will not be included for now as that has not been covered in the labs. A separate issue should be opened called "core/testing".

**Comment by rwx-yxu** [comment]
Pull request should only be merged in after **All** members have verified that they can start the app.

**Comment by rwx-yxu** [comment]
There are some confusing documentation out there. Misleading in fact. This docs https://bootstrap-vue.org/docs tries to tell you to add 'boostrap-vue' ontop of the 'bootstrap' npm package. Not required for our usage imo. We faced an error for 
```
X [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/bootstrap-vue/esm/vue.js:13:7:
      13 │ import Vue from 'vue';
         ╵        ~~~

X [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/bootstrap-vue/esm/vue.js:13:7:
      13 │ import Vue from 'vue';
         ╵        ~~~

X [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/bootstrap-vue/esm/vue.js:13:7:```
```

It is much simpler to just add the boostrap npm package standalone. Here is a useful doc site: https://larainfo.com/blogs/how-to-install-bootstrap-5-in-vue-3

**Comment by rwx-yxu** [comment]
### Group meeting
Having issues adding vitest and cypress retroactively to the project if not initially set up for vue init. When trying to run `npm run test:unit` or `npm run test:e2e`
```
npm ERR! Missing script: "test:unit"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
```

**Comment by rwx-yxu** [comment]
Could be worth to just make a new project with the testing setup.

**Comment by rwx-yxu** [comment]
Raised new branch to handle the setup https://github.com/advweb-grp1/advanced-web-final-year-project/tree/core/scaffold-v2

**Comment by rwx-yxu** [comment]
Had an issue for firebase github actions Resource not accessible by integration when trying to run the workflow. I managed to resolve it by changing the repo settings for actions 
![image](https://user-images.githubusercontent.com/33188164/226109759-44a7c5a7-6456-4296-a2aa-9e9563f195b6.png)
This is under the actions > general tab rather than the general tab

**Comment by rwx-yxu** [comment]
Current error is this
```  
 "status": "error",
    "error": "Directory 'dist' for Hosting does not exist."
```

**Comment by rwx-yxu** [comment]
Going to try to move all of the current vue code up one directory so we are not having to fight what is considered the working directory. Need to check if the cardiomyopathy directory is being referenced anywhere first in case it will have an unintended side effect.

**Comment by rwx-yxu** [comment]
Package.json references the cardiomyopathy name. I'll try to change the name to the repo name and run 'npm install' and 'npm run dev'

**Comment by rwx-yxu** [comment]
Github actions wasn't being triggered for my new commits to the pull requests because of the on pull_request_target option. This means that the latest action that was ran 7 hours ago was still being used which has an  old workflow file...

**Comment by rwx-yxu** [comment]
I'm going to add an action to be triggered for new commits on to a pull request and when it is opened. This would be valid for whenever we need to modify the workflow if our needs require it.
