### ISSUE TITLE
fix/x-axis labels

### ISSUE THREAD

**Issue by LiamSingh64** [advweb-grp1/advanced-web-final-year-project#61]
Currently, x-axis labels for the Line Charts on the Dashboard view are too closely bunched together
Two potential fixes include:
- Removing the labels completely with 
```
xaxis: { 
    labels: { 
        show: false 
        formatter: function(value){
              return "Particpant " + value;
        }
     } 
...}
```
Result: 
![987c68d8-d954-4cb7-af5f-c18e8e705125](https://user-images.githubusercontent.com/96130742/236335805-de0d7048-36ca-44f0-8906-de322b6b85c6.jpg)

- Have label contain "|" to create distinction and remove overlapping labels
```
xaxis: { 
  labels: { 
            rotate: 0,
            hideOverlappingLabels: true,
            formatter: function(value){
              return value + " |";
            }
  } 
...}
```
Result: 
![0d49b7d0-74b0-4674-81f5-1075d53886a9](https://user-images.githubusercontent.com/96130742/236335869-c90d30c5-ca4b-4a13-b9e6-509a2c65b0d0.jpg)

**Comment by rwx-yxu** [comment]
Both suggestions are not ideal. Instead, modify the category value on the x-axis. The category value expects an array which renders the labels for each item. By default since we are just passing nothing through, it will render each number for the data points.

**Comment by LiamSingh64** [comment]
Looks like xaxis.categories length needs to be the exact as series.data length, currently trying to find a way around this
