### ISSUE TITLE
 Register User

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#7]
## Summary
A user must register a username and password to access the system
## Basic Path
1. The use case starts when a user indicates that he/she wants to register.
1. The system requests a username (must be an email address) and password.
1. The user enters a username and password.
1. The system checks that the username does not duplicate any 
existing registered usernames.
1. The system requests a name (*), address, phone number, institutional affiliation (*) and email address (*). Items marked by (*) are required.
1. The user enters the information.
1. The system determines the user's location and stores all user information.
1. The system sends a verification email with a verification link to the user’s email address.
1. User clicks on link in email address.
1. User is redirected to a login page.
1. User logs in.
1. The system starts a login session and displays a welcome message.
## Alternative Paths
Step 4: If the username duplicates an existing username, the system displays a message and the use case goes back to step 2.
Step 5: If the user does not enter a required field, a message is displayed and the use case repeats step 4.
## Exception Paths
User already exists, in which case he/she can enter their password if known or request a password reset.
## Preconditions
The username is the user’s email address.
## Postconditions
The user can now access the system to add data, delete data, query data and visualise data

**Comment by advweb-grp1** [comment]
Investigate firebase API - for email activation

**Comment by advweb-grp1** [comment]
Might be on the slides. I would like an example piece of code here as demo.

**Comment by AymanReh** [comment]
Register component. User will need to insert **name**, address, phone number, **institutional affiliation**, **email** and **password**. (Items which are **bold**  are required)

**Comment by AymanReh** [comment]
### Register authentication
- Home page will contain a button called register once clicked the unregistered user will be sent to the register page( will be done using a route)
- Register form opens with 6 text boxes (Name(string), address(string), phone number(string), institutional affiliation(string), email(string) and password(string))
- Submit button below the 6 text boxes, when the submit button is pressed it will validate that all text boxes are not empty
- If the data has been validated connect register form to firebase auth using createUserWithEmailAndPassword
- Once data has been sent to the firebase authentication, it will insert the new user account into the database
- User will then be sent to the log-in page to log-in to their account.

### Validating data
- If data validation fails display an error to the user indicating what piece of data is incorrect e.g. password is empty. This will be implemented using a watcher.
- If a duplicate entry exists such as a username, then we can create a rule in the firebase database which checks for duplicate username data this can be done using:
match /users/{username} {allow create: if !exists(/databases/$(database)/documents/users/$(username))}
The code above will check if a username already exists, if it does it will not allow the duplicate data to be entered.


### User session
If a user is already logged in they should not be able to see the register button, this can be done by checking their session state

**Comment by AymanReh** [comment]
After doing some research on creating users in firebase, it seems like when a user creates an account using firebase they are automatically logged in.
Source: https://firebase.google.com/docs/auth/web/password-auth#create_a_password-based_account
![image](https://user-images.githubusercontent.com/46050460/230161446-d116ca50-06be-4cb2-adfa-9f4dd7706601.png)

**Comment by advweb-grp1** [comment]
Probably would want email validation using regular expressions.

**Comment by advweb-grp1** [comment]
Starting with the happy path first. For dev, use your own firebase project instance and auth.

**Comment by AymanReh** [comment]
After working on the register view it turns out that firebase automatically makes sure that there can be no duplicate data for the email, meaning no validation for email is required.

**Comment by AymanReh** [comment]
After implementing register user it seems like firebase only stores the email and password with the createUserWithEmailAndPassword command. So name, address, phone number and affiliation are not stored inside of the firebase authentication. Instead I can either store the data in a collection or store the data locally using something like a variable, but the problem is that it only stores the data on the users device instead of on firestore.

**Comment by AymanReh** [comment]
Ive updated feature/register to add user data to the database and added some validation for phone number. Now I need to add unit tests to test the register page.
