### ISSUE TITLE
Add Data

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#8]
## Summary
The user wants to add their experimental data to the repository
## Basic Path
1. The use case starts when a user indicates that he/she wants to add data to the system.
1. The system presents a dialog for the user to enter details regarding the data.
1. The system presents a dialog for the user to upload the data.
1. The user uploads data.
1. The system checks that the data file is the required format.
1. The system checks that there are only two columns of data (see preconditions).
1. The system stores the data.
1. The system adds and records a timestamp.
1. The system plots/graphs/charts the data.
1. The system sends a confirmation email to the user. Email should contain the recorded timestamp and other pertinent information.
## Alternative Paths
Step 4: If the file is the wrong format, the system displays a message and the use case repeats step 2.
Step 5: If other than two columns of data exist, a message is displayed and the use case repeats step 2.
## Exception Paths
The user can cancel the operation at any time.
## Preconditions
The data is stored in a csv file or developer-required format.
There are only two columns of data, e.g., force and time. [This is also the developer’s choice but there should be a verification of the format and the layout of the data].
## Postconditions
The data is now in the repository.

**Comment by D4ni3l8** [comment]
Add data component. The user fills in the form which contains textboxes which are force and time. When the user submits the form, a timestamp will be recorded. The file has to be in csv format.

**Comment by rwx-yxu** [comment]
Are we making two forms? One for manual user input and another file component?

**Comment by rwx-yxu** [comment]
If user uploads file. should we present a visual representation parsed as a preview? If so, that might very well be another component

**Comment by D4ni3l8** [comment]
I read the use case description again and the user uploads the data and it is stored in the repository in csv format. We dont need to make a preview.

**Comment by D4ni3l8** [comment]
- Create a button on dashboard that routes to the add data
- Create a form to complete the form
- Look at the firebase lab to post data
- Research on how to drag and drop files with bootstrap

**Comment by rwx-yxu** [comment]
Please list the high priority fields here for the form.
Create a new .js file in utils to parse and upload csv data. Check utils/uploadHcmData.js as an example for parsing and uploading data to firebase.

**Comment by rwx-yxu** [comment]
How are you going to add a route for add user data?

**Comment by D4ni3l8** [comment]
The high priority fields are:
a. left/right ventricular end diastolic volume (ledv/redv)
b. left/right ventricular end systolic volume (lesv/resv)
c. left/right ventricular ejection fraction (lvef/rvef)
d. left/right ventricular mass (lvmass/rvmass)
e. left/right systolic volume (lsv/rsv)
f. fibrosis/scarring (scar)
g. gender
h. age at MRI
i. apical HCM
j. sudden cardiac death
k. hypertension
l. diabetes
m. myectomy

a. MYH7
b. MYBPC3
c. TNNT2
d. ACTC
e. TPM1
f. TNNCI
g. TNNI3
h. MYL2
i. TT

I can make a route that takes the user to the add data page like this:
path: '/addData',
name: 'addData',
component: AddDataView

**Comment by advweb-grp1** [comment]
How to navigate to the new route? Button from the Dashboard?

**Comment by advweb-grp1** [comment]
Have you looked into file uploading component?

**Comment by D4ni3l8** [comment]
To navigate to the addData route, i could create a button in the navigation bar when the user is logged in or have a button for it on the dashboard.

****File uploading****
To upload data, i can use UseCSV which supports CSV and Excel files and allows me to drag and drop. To use UseCSV, i will need to create an account and then 'npm install @usecsv/vuejs3', then insert the import button with a template.

**Comment by D4ni3l8** [comment]
I ran the test and it failed. It says the server closed unexpectedly.

**Comment by advweb-grp1** [comment]
Decision made to use html tag with file type. Example: https://uploadcare.com/blog/html-file-upload-button/ .This solution is much more simpler than creating another external account because we already have some code that can parse the hcm data.

**Comment by advweb-grp1** [comment]
Do not need to implement sending email when data has been added.
