### ISSUE TITLE
Delete Data

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#9]
## Summary
The user wants to delete their experimental data from the repository.
## Basic Path
1. The use case starts when a user indicates that he/she wants to 
delete data from the system.
1. The system presents a dialog for the user to enter details regarding the data.
1. The system checks that the data exists.
1. The system authenticates and verifies the user credentials against the data.
1. The system retrieves the data.
1. The system asks for final confirmation from the user.
1. The system deletes the data.
1. The system records a timestamp.
1. The system displays a deletion confirmation message and sends a confirmation email to the user.
## Alternative Paths
Step 4: If the system is unable to verify the user’s credentials against the stored data, the system displays a message and repeats step 2.
Step 3: If the data does not exist, the system displays a message and repeats step 2.
## Exception Paths
The user can cancel the operation before step 7.
## Preconditions
The data exists in the repository.
## Postconditions
The data no longer exists in the repository.

**Comment by LiamSingh64** [comment]
I will be assuming the User has made a query that has returned data (either Heart or Personal) in a table format. When this table component is being generated, i'm thinking a simple button can be added onto the end of the table row, that may either have data associated with it or grabs data from the row it is on, and when clicked it uses that data (user_id/document_id) to delete the row. I think this will look quite streamlined.

Or, when the user click on some data/row, a modal appears with maybe the same form they used when inputting the data (for consistency) that is prepopulated with that data. And an Update and Delete button is there.

In terms of components, I don't think I will need anything massive, rather the allowance of a button in however we decide to show/display the data.

**Comment by advweb-grp1** [comment]
Prerequisite component assume would be a grid table of that lists out the data.

**Comment by LiamSingh64** [comment]
- Ensure there is a 'Composables' folder
- Make new function called **deleteDocument**
- Use boilerplate code from the slides to connect to Firestore using .env variables
- Find and note any Document ID for test purposes in Firestore console
- Make sure you can actually get document from Document ID
- Change boilerplate code so that this document can be deleted
- Verify document IS deleted
- Change 'Test Document ID' to ID of user chosen document - _**Blocker:**_ still need to determine HOW this will be done.
- Modify data displayed to include `<button @click="deleteDocument">Delete</button>`

**Comment by LiamSingh64** [comment]
## Composable Attempt
`async function deleteDocument(doc_id){`
`   const doc_ref = doc(firebaseStore, "hcm", doc_id);`
`   const docSnap = await getDoc(doc_ref);`
`   if( docSnap.exists() ){`
`      deleteDoc(docSnap.ref);`
`   }`
`}`

**Comment by advweb-grp1** [comment]
Do not need to send confirmation email to user.

**Comment by advweb-grp1** [comment]
Delete buttons should only appear on data that the user has added only.

**Comment by advweb-grp1** [comment]
Done
